---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check whether apache is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['httpd'] | length }} versions of apache already installed!"
  when: "'httpd' in ansible_facts.packages"

- name: Install Apache if it's not already installed
  ansible.builtin.yum:
    name: httpd
    state: latest
  when: "'httpd' not in ansible_facts.packages"

- name: Start apache service if it's not running
  ansible.builtin.service: 
    name: httpd
    state: started
    enabled: true
  register: apache_service

- name: Apache service status
  debug:
    var: apache_service.state


